Repository securesign/timestamp-authority, pull requests merged in 2023-09, with the labels that each got.

#3 :robot: triggering CI on branch 'redhat-v1.1.2' after synching from upstream/v1.1.2
  ci
Labels: kind/sync-fork-to-upstream, approved

#10 add github action
  .github/workflows/cronjobs.yaml
Labels: approved, lgtm

#13 rm cronjob,patchfile add Dockerfile
  .github/workflows/cronjobs.yaml
  redhat/overlays/Dockerfile
  redhat/patches/0001-dockerfile.patch
Labels: lgtm

#17 update script
  redhat/release/update-to-head.sh
Labels: approved, lgtm
