Repository securesign/timestamp-authority, pull requests merged in 2023-10, with the labels that each got.

#15 :robot: triggering CI on branch 'redhat-v1.1.2' after synching from upstream/v1.1.2
  Dockerfile
  ci
  redhat/release/update-to-head.sh
Labels: kind/sync-fork-to-upstream, approved

#21 :robot: triggering CI on branch 'redhat-v1.1.2' after synching from upstream/v1.1.2
  ci
Labels: kind/sync-fork-to-upstream, approved

#25 :robot: triggering CI on branch 'redhat-v1.1.2' after synching from upstream/v1.1.2
  ci
Labels: kind/sync-fork-to-upstream, approved

#29 update pipeline for new ws
  .tekton/timestamp-authority-pull-request.yaml
  .tekton/timestamp-authority-push.yaml
Labels: approved, lgtm

#31 SECURESIGN-115 | Add new label to dockerfiles for Comet
  redhat/overlays/Dockerfile
Labels: approved, lgtm

#33 chore: modify update script to avoid merge conflicts
  redhat/release/update-to-head.sh
Labels: approved, lgtm

#35 tests: update unit test task paths
  .tekton/timestamp-authority-pull-request.yaml
  .tekton/timestamp-authority-push.yaml
  .tekton/tsa-unit-test.yaml
Labels: approved, lgtm

#37 chore: update image shas for go-toolset ubi builder
  redhat/overlays/Dockerfile
Labels: approved, lgtm

#27 :robot: triggering CI on branch 'redhat-v1.1.2' after synching from upstream/v1.1.2
  Dockerfile
  ci
  redhat/overlays/Dockerfile
  redhat/release/update-to-head.sh
Labels: kind/sync-fork-to-upstream, approved

#41 feat: Add SHA check job
  .github/workflows/cronjobs.yaml
Labels: approved, lgtm

#40 update deploy base image
  redhat/overlays/Dockerfile
Labels: lgtm

#46 deps(gprc): update grpc dependency to 1.57.1
  redhat/overlays/go.mod
  redhat/overlays/go.sum
Labels: approved, lgtm

#44 :robot: triggering CI on branch 'redhat-v1.1.2' after synching from upstream/v1.1.2
  Dockerfile
  ci
  go.mod
  go.sum
Labels: kind/sync-fork-to-upstream, approved

#49 chore: remove unit tests from RHTAP pipeline
  .tekton/timestamp-authority-pull-request.yaml
  .tekton/timestamp-authority-push.yaml
Labels: approved, lgtm
